### ISSUE TITLE
npz and indices for texture

### ISSUE THREAD

**Issue by jackie-vifive** [MiraPurkrabek/RePoGen#7] opened 2023-11-10 22:01 UTC
Hello,

Thanks again for the wonderful work and support.

I had a question about this block of the code from `sample_random_poses.py`
It seems like we are loading the "repogen_MALE_indices.npz" file for loading the pre-computed mapping of vertices.
From the SMPL-X website, however, I was only able to get "SMPLX_MALE.npz" which doesnt have the required key, "indices". 
I wanted to clarify that the required repogen_MALE_indices.npz is different from SMPLX_MALE.npz. 

I came across obj_to_vertices.py in the tools directory, and perhaps we can generate the *_indices.npz from the *uv.obj file. However, this script also requires `orig_vertices = np.load("images/textures/vertices_generated.npz")["vertices"]` and I couldn't figure out where this file comes from. 

I am trying to reproduce this work on my end and included textures to the model, but the pose is not being altered from the T-pose when I add texture. I am suspecting this is the part that needs to be addressed to get it to work. 

Please let me know if you need any clarifications to my inquiry!

```
indices_path = os.path.join(
        "textures",
        texture_folder,
        "mappings",
        "repogen_MALE_indices.npz",
    )
    obj_path = os.path.join(
        "textures",
        texture_folder,
        "mappings",
        "repogen_UV.obj",
    )

    # Load the texture image with OpenCV
    if args is not None and args.show:
        im = cv2.imread(texture_path)[:, :, ::-1]
    else:
        im = cv2.imread(texture_path)

    # Load the OBJ file with UV map
    m = trimesh.load(obj_path)

    # Load the pre-computed mapping from 10475 to 11313 vertices
    indices_to_sort = np.load(indices_path)["indices"]
    m.vertices = vertices[indices_to_sort, :]
```

**Comment by MiraPurkrabek** [comment] 2024-01-19 10:07
Hi @jackie-vifive ,
Sorry for the late reply, I did not notice the issue.

The indices are indeed the same as of the SMPLX model and should be downloaded along with other files.The error was caused by typo fixed by #10 . Now the code should be more readable.

Please, let me know if this solved you issue.

**Comment by EWE002** [comment] 2024-01-26 05:51
Hi, @jackie-vifive 
I would like to ask if you have encountered the following problem when running obj_to_indices.py?
File "tools/obj_to_indices.py", line 14, in <module>
    from examples.sample_random_poses import random_camera_pose
ModuleNotFoundError: No module named 'examples'
If not, where is your random_camera_pose?
Thank you in advance.

**Comment by jackie-vifive** [comment] 2024-01-26 16:47
I also had trouble generating the vertices_generated.npz. 

Not sure if this is the correct way to do it, but I added these lines in `sample_random_poses.py` to generate the npz file.
I don't think the vertices are gender dependent, 

```
            if args.save_default_pose:
                gndr = "male"

                model = repogen.create(
                    args.model_folder,
                    model_type=args.model_type,
                    gender=gndr,
                    use_face_contour=args.use_face_contour,
                    num_betas=args.num_betas,
                    num_expression_coeffs=args.num_expression_coeffs,
                    ext=args.model_ext,
                )
                npz_file_path = "default_vertices.npz"
                default_output = model()
                default_vertices = default_output.vertices.detach().cpu().numpy().squeeze()

                np.savez(npz_file_path, default_vertices=default_vertices)
```

**Comment by MiraPurkrabek** [comment] 2024-02-10 09:27
Hi, 
as mentioned in #11 , I can not find the reference to *vertices_generated.npz* at the moment so please use the link to directly download *SMPLX_MALE_indices.npz*.

Link: https://drive.google.com/file/d/13osjQAbgCJD4hgDr3BUAyC40r2QfV8-P/view?usp=sharing

**Closed** 2024-03-13 08:57 UTC
