### ISSUE TITLE
How do I generate my own synthesized data?

### ISSUE THREAD

**Issue by EWE002** [MiraPurkrabek/RePoGen#9] opened 2024-01-19 07:59 UTC
Thanks for such an innovative work!
I would like to ask how to create my own random synthesized data if I want to?
Right now I've followed the README and put the model(smplx) into the models folder, but after running the
python scripts/sample_random_poses.py
I get
Generating poses and views...
  0%| | 0/2 [00:00<? , ?it/s]
Traceback (most recent call last).
  File "scripts/sample_random_poses.py", line 767, in <module>
    main(args)
  File "scripts/sample_random_poses.py", line 241, in main
    model = repogen.create(
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/repogen/body_models.py", line 2644, in create
    raise ValueError(f "Unknown model type {model_type}, exiting!")
ValueError: Unknown model type repogen, exiting!
What parameters do I need to add?
Thank you in advance!

**Comment by MiraPurkrabek** [comment] 2024-01-19 10:04
Hi, 
there was a typo in the code that prevented you from running the script easily. The typo is now fixed by #10 .
Thanks for pointing this out.

If the problem is solved, please close the issue.

**Comment by EWE002** [comment] 2024-01-20 13:09
Thank you very much for your answer, about the previous problem has been solved, but now there is a new problem:...
Generating poses and views...
  0%| | 0/2 [00:00<? , ?it/s]
Traceback (most recent call last): File "scripts/sample_rr".
  File "scripts/sample_random_poses.py", line 767, in <module>
    main(args)
  File "scripts/sample_random_poses.py", line 304, in main
    tri_mesh = get_textured_mesh(vertices, texture_path=None, args=args)
  File "scripts/sample_random_poses.py", line 111, in get_textured_mesh
    texture_folder = np.random.choice(os.listdir("textures"))
FileNotFoundError: [Errno 2] No such file or directory: 'textures'
Where should I put the texture folder? And is textures the same as backgrounds, just google for images?

**Closed** 2024-01-21 06:21 UTC
